apiVersion : apps/v1
kind: Deployment
metadata:
  name: umbdemobackend 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: umbdemobackend
  template:
    metadata:
      labels:
        app: umbdemobackend 
    spec:
      containers:
        - name: umbdemobackend 
          image: chaeschpi.azurecr.io/umbdemobackend
          ports:
          - containerPort: 80